import Link from "next/link";
import { Mail, MapPin, Phone } from "lucide-react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { siteInfo } from "@/lib/site-content";

export default function ContactPage() {
  return <main className="bg-white text-[#071b3e]"><SiteHeader /><section className="bg-[#edf3f8] px-5 pb-24 pt-36 sm:px-8"><div className="mx-auto max-w-6xl"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#a97f16]">Contact</p><h1 className="mt-5 font-serif text-6xl leading-tight">Let’s talk about your next step.</h1><p className="mt-6 text-lg leading-8 text-[#607087]">These contact details are placeholders while the college’s verified campus and intake information is finalised.</p><div className="mt-10 grid gap-5"><a href={`mailto:${siteInfo.email}`} className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-full bg-white"><Mail size={19}/></span><span>{siteInfo.email}</span></a><a href={siteInfo.phoneHref} className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-full bg-white"><Phone size={19}/></span><span>{siteInfo.phone}</span></a><p className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-full bg-white"><MapPin size={19}/></span><span>{siteInfo.address}</span></p></div></div><div className="rounded-[32px] bg-white p-8 shadow-[0_24px_70px_rgba(7,27,62,.08)] sm:p-10"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#a97f16]">Register your interest</p><h2 className="mt-4 font-serif text-4xl">Tell us which sample pathway interests you.</h2><p className="mt-5 leading-7 text-[#607087]">Use the enrolment form to share your details. Submitting interest does not create a financial obligation or confirm a place.</p><Link href="/enroll" className="mt-8 inline-flex rounded-full bg-[#071b3e] px-6 py-4 font-bold text-white">Open interest form</Link></div></div></div></section><SiteFooter /></main>;
}
